### PR TITLE
Don't attempt to save when a current request is in flight.

### LINKED ISSUE #74: ArchiveComponent onCollapse duplicates images
Since records are persisted on each collapse an image may be saved to the wrong record.

### onCollapse Save:
https://github.com/PronghornDigital/Montana-News-Archive/blob/master/src/client/mtna/archive-component.ts#L123

### Reproduce
Rapidly expand and collapse several records
Check each record for additional images

### PR DESCRIPTION
**Pull request by DavidSouther**
I think this will fix #74; @JonathanPorta can you verify locally?

### CODE REVIEW

**Comment by stanparker** [comment]
Thanks, David!

It certainly is snappier when clicking around from record to record.

The biggest problem I see with this is the way we currently handle the "Notes" field. Someone could type a note in and expect it to save when they click another record, but it would wipe out their notes.

**Comment by DavidSouther** [comment]
I don't think so? This is supposed to only prevent saving *while another record is actively saving*. That is, during the couple seconds from closing one to opening the next, and then closing it while the first is still in flight. That ought to be quick enough that if someone were to start typing notes, the first request would finish in time.

**Comment by stanparker** [comment]
I went back and checked. If you add a note to a record and then click on a
different one, the note will remain there only until you refresh the page,
at which point it gets blipped out of existence.

**Comment by DavidSouther** [comment]
@stanparker as we discussed on chat, this should solve that.

**Comment by stanparker** [comment]
Thanks, looks good!

**Pull request merged**
