### PR TITLE
Bug/allow duplicate slugs

### PR DESCRIPTION
**Pull request by DavidSouther**
I don't think this is ready to merge, yet. For now, it does:

#40 Need a way to edit stories
#70 Allow duplicate slugs

I want to keep working on it to also cover

#80 submit/return does not save a story record
#89 When collapsing after editing, a save error shows
#91 don't save on collapse.

### CODE REVIEW

**Comment by stanparker** [comment]
This is great. A few thoughts

- Should have a way to delete slugs
- I don't know if you need the "+" button. I think maybe it could always have an open input field with placeholder text that says "add a story here" or something. Then when you hit "Save" it automatically queues up a new one for you.
- Hitting "Enter" should save
- It kind of bothers me that somebody could spend 20 minutes transcribing an index, and then if they close out of their browser window before collapsing the record, they would lose their work. Perhaps we could replace the "+" with a Save button?
- Block blank slugs

**Comment by DavidSouther** [comment]
> I don't know if we need the "+" button. I think maybe it could always have an open input field with placeholder text that says "add a story here" or something. Then when you hit "Save" it automatically queues up a new one for you.

You expressly did not like the way we handled that before.

> Hitting "Enter" should save
> Perhaps we could replace the "+" with a Save button?
I am making the "save" button at row level also trigger save. Additionally, I could make it so you can only edit a single record at a time; thus, you would *never* be more than one story away from saved.

> Block blank slugs
Entirely? How? Remove them when saving? That's a bit too vague. What if the user has filled out date, format, and runtime? Need a bit more guidance from you on that one.

> Delete stories
Hypothetically, we could do that with Blank Slugs. If the slug is blank, it's "delete" instead of "save" on the right hand icon. (And also an angry red?)

**Comment by DavidSouther** [comment]
We now:

Focus the slug input when editing.

Remove stories when their slug is empty (with a big red delete button).

We do not: save stories when hitting "enter" on the field, you must tab to the "save" button.
@stanparker Please confirm that this last part is reasonable for closing #80

**Comment by stanparker** [comment]
All good. Thanks, David.

**Pull request merged**
