### PR TITLE
Search within stories.

### LINKED ISSUE #64: Search String Should Search Within Stories Too
When searching with a string in the search field, results should also be returned where there is a match within the slugs of the stories on the record.

### PR DESCRIPTION
**Pull request by DavidSouther**
Closes #64

### CODE REVIEW

**Comment by stanparker** [comment]
Nice. Seems to work great. Okay to merge?

**Comment by DavidSouther** [comment]
If you like it!

**Comment by stanparker** [comment]
Cool -- looks like we've got some conflicts now after merging the delete button.

**Comment by DavidSouther** [comment]
You can merge when Travis finishes.

**Comment by stanparker** [comment]
Travis likes it.

**Pull request merged**
