### PR TITLE
Update media links when renaming records.

### LINKED ISSUE #100: Renaming Labels Breaks Media Links
When labels are renamed, paths to video and photos break.

### PR DESCRIPTION
**Pull request by DavidSouther**
Closes #100

### CODE REVIEW

**Comment by stanparker** [comment]
Hmm...... now when renaming a record it tries to embed a video for everything it was renamed to:

```
<div flex-gt-md="25" layout="column" layout-md="row" layout-sm="row" class="layout-sm-row layout-md-row layout-column flex-gt-md-25"><!-- ngRepeat: video in state.record.videos --><div flex-md="50" ng-repeat="video in state.record.videos" class="ng-scope flex-md-50"><video controls="controls" class="ng-binding"><source ng-src="/images/courtney_2abcdefe/courtney002.mp4" type="video/mp4" src="/images/courtney_2abcdefe/courtney002.mp4">Can't play video: {
  "path": "courtney_2abcdefe/courtney002.mp4"
}</video></div><!-- end ngRepeat: video in state.record.videos --><div flex-md="50" ng-repeat="video in state.record.videos" class="ng-scope flex-md-50"><video controls="controls" class="ng-binding"><source ng-src="/images/courtney_2abcdefeabc/courtney002.mp4" type="video/mp4" src="/images/courtney_2abcdefeabc/courtney002.mp4">Can't play video: {
  "path": "courtney_2abcdefeabc/courtney002.mp4"
}</video></div><!-- end ngRepeat: video in state.record.videos --><div flex-md="50" ng-repeat="video in state.record.videos" class="ng-scope flex-md-50"><video controls="controls" class="ng-binding"><source ng-src="/images/courtney_2/courtney002.mp4" type="video/mp4" src="/images/courtney_2/courtney002.mp4">Can't play video: {
  "path": "courtney_2/courtney002.mp4"
}</video></div><!-- end ngRepeat: video in state.record.videos --><div flex-md="50" ng-repeat="video in state.record.videos" class="ng-scope flex-md-50"><video controls="controls" class="ng-binding"><source ng-src="/images/courtney_2abc/courtney002.mp4" type="video/mp4" src="/images/courtney_2abc/courtney002.mp4">Can't play video: {
  "path": "courtney_2abc/courtney002.mp4"
}</video></div><!-- end ngRepeat: video in state.record.videos --><div flex-md="50" ng-repeat="video in state.record.videos" class="ng-scope flex-md-50"><video controls="controls" class="ng-binding"><source ng-src="/images/courtney_2abcabc/courtney002.mp4" type="video/mp4" src="/images/courtney_2abcabc/courtney002.mp4">Can't play video: {
  "path": "courtney_2abcabc/courtney002.mp4"
}</video></div><!-- end ngRepeat: video in state.record.videos --><div flex-md="50" class="flex-md-50"><md-input-container style="width: 15em; height: auto;" class="md-input-has-placeholder"><label for="input_5">Notes</label><textarea ng-model="state.record.notes" placeholder="Notes" class="ng-pristine ng-untouched ng-valid md-input ng-empty" id="input_5" rows="1" aria-invalid="false" style="height: 32px;"></textarea><div class="md-errors-spacer"></div></md-input-container></div></div>
```

**Comment by stanparker** [comment]
To replicate:

1. Navigate to server
2. Create new record with label "Video Test Rename"
3. Add a video
4. Collapse the record
5. Open it
6. Click Edit
7. Change the label to "Video Test Remix"
8. Click Done
9. Collapse Record
10. Open it to see the video and a blank video player connected to nothing.

**Comment by stanparker** [comment]
[Screenshot of step 10 in list above](http://i.imgur.com/bceHd2M.png)

**Comment by stanparker** [comment]
not quite ready yet

**Comment by stanparker** [comment]
Tested OK. Good to merge?

**Comment by DavidSouther** [comment]
Yep

**Pull request merged**
