### PR TITLE
Fix weird behavior on "new" when "editing"

### LINKED ISSUE #48: Odd Behaviors When Clicking "New" When Card is Open
When clicking "New" when a card is open, it doesn't go to the edit state, and doesn't scroll all the way down to the bottom to see it.

### PR DESCRIPTION
**Pull request by DavidSouther**
Closes #48

### CODE REVIEW

**Comment by stanparker** [comment]
Hmmm.... this only seems to work about half the time, and I can't figure out what the difference is between when it works and when it doesn't.

**Comment by DavidSouther** [comment]
Let me know if you want to get on video.

**Comment by stanparker** [comment]
Hmmm.. it still doesn't fix the issue for me. It seems like the first time I try to create a new record on a fresh load of a page, it still doesn't default to edit state and doesn't scroll down.

**Comment by stanparker** [comment]
test ok. merging.

**Pull request merged**
