### PR TITLE
URL encodes search and selected record.

### PR DESCRIPTION
**Pull request by DavidSouther**
BIG BUG: Dates are all mucked up.

Implements #45

### CODE REVIEW

**Comment by stanparker** [comment]
Do not merge.

**Comment by DavidSouther** [comment]
Also add ability to have *no* search query.

**Comment by DavidSouther** [comment]
URL Forms:

/query/start+end/id
/start+end/id
/query/id

**Comment by DavidSouther** [comment]
@stanparker this should have the weird Date.getMonth issues sorted out.

**Comment by stanparker** [comment]
Okay, awesome! Is this ready to merge?

**Comment by DavidSouther** [comment]
Yeah, I think so!

**Comment by stanparker** [comment]
Cool. Merging this sucker.

**Pull request merged**
