### PR TITLE
Bug/delete record

### PR DESCRIPTION
**Pull request by DavidSouther**
Closes #24.

This needs some TLC & testing - it gets a bit odd with records in inconsistent state, after the `rename and move` issues in #100

### CODE REVIEW

**Comment by stanparker** [comment]
First thing I noticed was that the deleted records keep showing on the page until you refresh, and tape folders don't get deleted.

Test case

1. Navigate to localhost:8080
2. Create a new record called Demetrius 5
3. Add an image
4. Refresh the page
5. Search for "demetrius"
6. Click on the Demetrius 5 record
7. Click edit, then delete, then confirm the deletion
8. Notice that Demetrius 5 still appears in the search results
9. Refresh the page to see that it is now gone
10. Notice that the demetrius_5 folder still exists in the /data folder

**Comment by DavidSouther** [comment]
Those two issues are fixed. I need to add tests, but you could get a start on verifying them :)

**Comment by stanparker** [comment]
Cool, thanks man. 8 and 10 seem to be fixed. 

Found a couple more issues. 

A. It doesn't want to delete records that don't have any media attached:
1. Navigate to localhost:8080
2. Create a new record with label "Django 1" and add no media
3. Search for the record and open it
4. Click Edit > Delete > Yes
5. Toast error gives:

```
{"data":{"errno":-2,"code":"ENOENT","syscall":"rmdir","path":"/var/archives/data/django_1"},"status":500,"config":{"method":"DELETE","transformRequest":[null],"transformResponse":[null],"url":"/api/records/django_1","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Internal Server Error"}
```

B. Delete doesn't work for records if their label field has been modified, but not written

1. Create a new record with label Django 5
2. Add an image
3. Close and search for the record
4. Open it
5. Click Edit
6. Modify the label to Django 5 - abc, but don't click done
7. Click Delete, then Yes.
8. Following errors occur:

Console Error Shows:
```
Cannot read property 'videos' of undefined
    at RecordHandler.delete (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/dist/api/record/record.js:238:41)
    at _.handler (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/ts-rupert/dist/plugin/plugin.js:50:24)
    at Layer.handle [as handle_request] (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/layer.js:95:5)
    at /Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:277:22
    at param (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:410:3)
TypeError: Cannot read property 'videos' of undefined
    at RecordHandler.delete (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/dist/api/record/record.js:238:41)
    at _.handler (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/ts-rupert/dist/plugin/plugin.js:50:24)
    at Layer.handle [as handle_request] (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/layer.js:95:5)
    at /Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:277:22
    at param (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:410:3)
```
Toast Error Shows:
```
{"data":"TypeError: Cannot read property &#39;videos&#39; of undefined<br> &nbsp; &nbsp;at RecordHandler.delete (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/dist/api/record/record.js:238:41)<br> &nbsp; &nbsp;at _.handler (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/ts-rupert/dist/plugin/plugin.js:50:24)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at param (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:349:14)<br> &nbsp; &nbsp;at param (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at Function.process_params (/Users/stanparker/Devel/PronghornDigital/Montana-News-Archive/node_modules/express/lib/router/index.js:410:3)\n","status":500,"config":{"method":"DELETE","transformRequest":[null],"transformResponse":[null],"url":"/api/records/django_5_-_abc","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Internal Server Error"}
```

**Comment by stanparker** [comment]
Alrighty, lookin good. I'll merge.

**Pull request merged**
